default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce
  username: postgres
  password: 01240904
  host: localhost

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: ecommerce_test
  pool: 5
  username: postgres
  password: 01240904
  host: 127.0.0.1
  port: 5432

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV['PGDATABASE'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
