default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shop_development

test:
  <<: *default
  database: shop_test

production:
  <<: *default
  database: shop_production
  username: postgres
  password: root
